#!/bin/sh

USER="[[drone.user]]"
GROUP="[[drone.group]]"
APP_NAME="[[drone.app.name]]"

set -e

case "$1" in
    purge)
        if which deluser >/dev/null 2>&1; then
            deluser --quiet "$USER" > /dev/null || true
        fi
        
        delgroup --quiet "$GROUP" > /dev/null || true

        rm -r "/var/lib/$APP_NAME" || true
    ;;
esac

exit 0